### ISSUE TITLE
PHP ftplugin needs a maintainer

### ISSUE THREAD

**Issue by dkearns** [TysonAndre/vim-syntax#17]
G'day,

The distributed PHP ftplugin is currently [without a maintainer](https://github.com/vim/vim/pull/9821#issuecomment-1057927526).  Would you consider maintaining it here alongside the syntax file?

Thanks,
Doug

**Comment by TysonAndre** [comment]
I don't use the ftplugin settings (run after including a file type) that often (I depend on them much less than syntax) so I'm not that familiar with them and don't plan to take over maintaining them 

Other functionality I had to look up because I've never used them, leaving a note on impressions anyway

- include hasn't changed
- browsefilter could include `*.phpt` but that's specific to only pecl extension test cases which is a much less common use case
- `[[` overrides - I haven't used the section command overrides (or known about that overridden shortcut) but it's missing the recent additions of trait, enum
- haven't used matchit but it hasn't really changed

```
							*browsefilter*
For MS-Windows and GTK, you can modify the filters that are used in the browse
dialog.  By setting the g:browsefilter or b:browsefilter variables, you can
change the filters globally or locally to the buffer.  The variable is set to
```

**Comment by dkearns** [comment]
OK, thanks for the feedback.

I'll take over maintenance and look at updating it and integrating your suggestions.
